autoload -U colors && colors
autoload -Uz compinit && compinit
autoload -Uz vcs_info
setopt prompt_subst

# VARIABLES
NEWLINE=$'\n'

# FUNCTIONS
precmd() {
    local gstat="$(git status 2> /dev/null)"
    if [[ $gstat =~ "working directory clean" ]]; then
        zstyle ':vcs_info:*' formats "(%F{green}%b%f)"
    else
        zstyle ':vcs_info:*' formats "(%F{red}%b%f)"
    fi

    vcs_info
}

# THE PROMPT
PS1='${NEWLINE}%~ ${vcs_info_msg_0_}${NEWLINE}$ '
# PATH
export PATH="/usr/local/sbin:$PATH"

# ALIASES
alias ls='ls -GF'
alias gc='git commit -m'
alias gca='git commit -am'
alias gstat='git status'
alias gadd='git add .'
alias gdiff='git diff'
alias gdiffc='git diff --cached'
alias gco='git checkout'
alias gb='git branch'
alias gcob='git checkout -b'
alias gpushom='git push origin master'
alias hlt='heroku logs --tail'
alias gpushhm='git push heroku master'
alias gpushmm='git push mirror master'
alias bupdate='brew update'
alias bdoc='brew doctor'
alias boutdated='brew outdated'
alias bupgradeall='brew upgrade --all'
alias cdp='cd ~/www/personal'
alias cdsc='cd ~/www/SoundCollective'
alias msc='mongo soundcollective'
alias cdwild='cd $HOME/www/php/Wild/wp-content/themes/Divi-child'
alias cddots='cd ~/bin/dotfiles'
alias ls='ls -G'
