autoload -U colors && colors
PROMPT="%n@%m %~ "

alias gc='git commit -m'
alias gstat='git status'
alias gadd='git add .'
alias gpushom='git push origin master'
alias hlt='heroku logs --tail'
alias gpushhm='git push heroku master'
alias bupdate='brew update'
alias bdoc='brew doctor'
alias cdp='cd ~/www/personal'
alias cdsc='cd ~/www/SoundCollective'
alias msc='mongo soundcollective'
