runtime! archlinux.vim
set nocompatible
set t_Co=256
execute pathogen#infect()
syntax on
set background=dark
colorscheme atom-dark
filetype plugin indent on
set number
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set backspace=2
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set splitbelow
set splitright

"auto commands
"autocmd BufRead,BufWritePre *.html,*.js normal gg=G

augroup HTMLCmds
	autocmd!
	autocmd Filetype html nnoremap <leader>ku I<!--<esc>A--><esc>
augroup END


augroup JavaScriptCmds
	autocmd!
	autocmd Filetype javascript nnoremap <leader>ku I//<esc>
augroup END

let g:netrw_winsize=15
