runtime! archlinux.vim
set nocompatible
set t_Co=256
set encoding=utf-8
set fileencoding=utf-8
execute pathogen#infect()
syntax on
set background=dark
colorscheme atom-dark
filetype plugin indent on
set number
set autoindent
set cindent
set shiftwidth=4
set tabstop=4
set expandtab
set backspace=2
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set splitbelow
set splitright

if has('persistent_undo')
    set undofile
    set undodir=$HOME/.vim/undo
endif

"auto commands
"autocmd BufRead,BufWritePre *.html,*.js normal gg=G

augroup HTMLCmds
	autocmd!
	autocmd Filetype html nnoremap <leader>ku I<!--<esc>A--><esc>
augroup END


augroup JavaScriptCmds
	autocmd!
	autocmd Filetype javascript nnoremap <leader>ku I//<esc>
augroup END

let g:netrw_winsize=15
if has("win32") || has("win16")
	" Use ~x on an English Windows version or ~n for French.
	au GUIEnter * simalt ~x
	set guifont=Consolas:h11
endif

"NERDTree Settings
let g:NERDTreeDirArrows = 1
" VIM will close if NERDTree is the only window
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" Open NERDTree when Vim starts
autocmd vimenter * NERDTree
" Toggle NERDTree
map <C-n> :NERDTreeToggle<CR>

"Syntastic Settings
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_eslint_exec = 'eslint_d'
